[package]
name = "dbm"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
askama_actix = "0.13.0"
askama = "0.11.1"
serde = "1"
sqlx = { version = "0.6", features = ["runtime-actix-native-tls", "postgres"] }